# -*- coding: utf-8 -*-
"""Multimodal Module

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nwK0xjjNETf0WZaRHpDGGjPzDs4reBf
"""

# -*- coding: utf-8 -*-
"""
Perceptor Module (Eyes & Ears).
Отвечает за транскрибацию аудио и анализ изображений.
Умеет конвертировать HEIC -> JPG на лету.
"""

import os
import asyncio
import logging
import time
import uuid
import base64
import mimetypes
import re
import json
import threading
import subprocess
import sys
import edge_tts
from typing import Dict, Any, Optional
from io import BytesIO
from PIL import Image
from pillow_heif import register_heif_opener
from pathlib import Path
import aiohttp

# Регистрируем поддержку HEIC для Pillow
register_heif_opener()

logger = logging.getLogger(__name__)

# Gemini SDK (New v1.0+)
try:
    from google import genai
    from google.genai import types
    _GENAI_AVAILABLE = True
except ImportError:
    _GENAI_AVAILABLE = False
    genai = None

class Perceptor:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        # Whisper-модель из конфига вместо хардкода
        self.whisper_model = config.get("WHISPER_MODEL", os.getenv("WHISPER_MODEL", "mlx-community/whisper-large-v3-turbo"))
        # Vision-модель из .env (убрали хардкод gemini-2.0-flash)
        self.vision_model = os.getenv("GEMINI_VISION_MODEL", "gemini-2.0-flash")
        # Локальный vision через LM Studio (опционально).
        self.local_vision_enabled = str(
            os.getenv("LOCAL_VISION_ENABLED", str(config.get("LOCAL_VISION_ENABLED", "0")))
        ).strip().lower() in {"1", "true", "yes", "on"}
        self.local_vision_model = str(
            os.getenv("LOCAL_VISION_MODEL", str(config.get("LOCAL_VISION_MODEL", "")))
        ).strip()
        self.local_vision_timeout_seconds = float(
            os.getenv(
                "LOCAL_VISION_TIMEOUT_SECONDS",
                str(config.get("LOCAL_VISION_TIMEOUT_SECONDS", "90")),
            )
        )
        self.local_vision_max_tokens = int(
            os.getenv(
                "LOCAL_VISION_MAX_TOKENS",
                str(config.get("LOCAL_VISION_MAX_TOKENS", "1200")),
            )
        )
        
        self.gemini_key = config.get("GEMINI_API_KEY") or os.getenv("GEMINI_API_KEY")
        self.stt_language = str(
            config.get("STT_LANGUAGE", os.getenv("STT_LANGUAGE", "ru"))
        ).strip() or "ru"
        self.stt_temperature = float(
            config.get("STT_TEMPERATURE", os.getenv("STT_TEMPERATURE", "0.0"))
        )
        self.stt_beam_size = int(
            config.get("STT_BEAM_SIZE", os.getenv("STT_BEAM_SIZE", "7"))
        )
        self.stt_best_of = int(
            config.get("STT_BEST_OF", os.getenv("STT_BEST_OF", "5"))
        )
        self.stt_patience = float(
            config.get("STT_PATIENCE", os.getenv("STT_PATIENCE", "1.0"))
        )
        self.stt_condition_on_previous_text = str(
            config.get(
                "STT_CONDITION_ON_PREVIOUS_TEXT",
                os.getenv("STT_CONDITION_ON_PREVIOUS_TEXT", "1"),
            )
        ).strip().lower() in {"1", "true", "yes", "on"}
        self.stt_no_speech_threshold = float(
            config.get(
                "STT_NO_SPEECH_THRESHOLD",
                os.getenv("STT_NO_SPEECH_THRESHOLD", "0.45"),
            )
        )
        self.stt_compression_ratio_threshold = float(
            config.get(
                "STT_COMPRESSION_RATIO_THRESHOLD",
                os.getenv("STT_COMPRESSION_RATIO_THRESHOLD", "2.4"),
            )
        )
        self.stt_hotwords = self._parse_hotwords(
            config.get("STT_HOTWORDS", os.getenv("STT_HOTWORDS", ""))
        )
        self.stt_replace_map = self._parse_replace_map(
            config.get("STT_REPLACE_JSON", os.getenv("STT_REPLACE_JSON", ""))
        )
        # MLX Whisper может падать на параллельных вызовах (Metal/AGX assert),
        # поэтому сериализуем все STT-задачи одним локом.
        self._transcribe_lock = asyncio.Lock()
        # Дополнительная защита: запуск STT в отдельном процессе.
        # Если MLX/Metal падает (SIGABRT), упадет только воркер, а не весь Krab.
        isolated_default = "1"
        if "PYTEST_CURRENT_TEST" in os.environ:
            # В тестах по умолчанию оставляем in-process путь для стабильных моков.
            isolated_default = "0"
        self.stt_isolated_worker = str(
            config.get(
                "STT_ISOLATED_WORKER",
                os.getenv("STT_ISOLATED_WORKER", isolated_default),
            )
        ).strip().lower() in {"1", "true", "yes", "on"}
        self.stt_worker_timeout_seconds = int(
            config.get(
                "STT_WORKER_TIMEOUT_SECONDS",
                os.getenv("STT_WORKER_TIMEOUT_SECONDS", "240"),
            )
        )
        # Последний фактический маршрут vision для прозрачной диагностики.
        self.last_vision_meta: Dict[str, Any] = {
            "route": "unknown",
            "model": "",
            "fallback_used": False,
            "local_enabled": bool(self.local_vision_enabled),
            "error": "",
        }
        
        logger.info(f"👂 Perceptor initialized. Audio: {self.whisper_model}, Vision: {self.vision_model}")

        # Warmup MLX в фоне.
        # По умолчанию выключен, т.к. на части macOS/MLX-конфигураций
        # прогрев может аварийно завершать процесс (AGX assert) до старта Web API.
        warmup_enabled = str(
            config.get("PERCEPTOR_AUDIO_WARMUP", os.getenv("PERCEPTOR_AUDIO_WARMUP", "0"))
        ).strip().lower() in {"1", "true", "yes", "on"}
        if warmup_enabled:
            threading.Thread(
                target=self._warmup_audio,
                name="perceptor-mlx-warmup",
                daemon=True,
            ).start()
        else:
            logger.info("Perceptor MLX warmup disabled by PERCEPTOR_AUDIO_WARMUP=0")

    def _warmup_audio(self):
        """Прогрев Neural Engine для MLX Whisper."""
        try:
            import mlx_whisper
            import numpy as np
            logger.info("🔥 Warming up Neural Engine (MLX)...")
            # Прогрев тишиной
            mlx_whisper.transcribe(np.zeros(16000, dtype=np.float32), path_or_hf_repo=self.whisper_model)
            logger.info("✅ MLX Audio Model Ready.")
        except Exception as e:
            logger.warning(f"MLX Warmup Skipped: {e}")

    async def transcribe(self, file_path: str, router) -> str:
        """
        Транскрибирует аудио с помощью MLX Whisper (Local).
        """
        try:
            async with self._transcribe_lock:
                logger.info(f"🎤 Transcribing: {file_path}")

                start_time = time.time()

                if self.stt_isolated_worker:
                    result = await self._run_mlx_transcribe_isolated(file_path=file_path)
                else:
                    import mlx_whisper
                    # Запускаем в executor, чтобы не блокировать event loop (MLX тяжелый).
                    # Часть аргументов может не поддерживаться конкретной версией mlx_whisper,
                    # поэтому сначала пробуем расширенный профиль, затем безопасный fallback.
                    result = await self._run_mlx_transcribe_with_fallback(
                        mlx_whisper=mlx_whisper,
                        file_path=file_path,
                    )

                worker_error = str(result.get("_worker_error", "")).strip()
                if worker_error:
                    raise RuntimeError(worker_error)

                raw_text = str(result.get("text", "")).strip()
                text = self._postprocess_transcript(raw_text)
                duration = time.time() - start_time

                logger.info(f"✅ Transcribed in {duration:.2f}s: {text[:50]}...")
                return text

        except Exception as e:
            logger.error(f"❌ Local Transcription Failed: {e}")
            return f"Ошибка транскрибации: {e}"

    def _parse_hotwords(self, raw: Any) -> list[str]:
        """Парсит список подсказок для STT из строки 'a,b,c'."""
        text = str(raw or "").strip()
        if not text:
            return []
        return [token.strip() for token in text.split(",") if token.strip()]

    def _parse_replace_map(self, raw: Any) -> dict[str, str]:
        """
        Парсит словарь замен распознанного текста из JSON-строки.
        Пример:
        {"джимени":"Gemini","оупен кло":"OpenClaw"}
        """
        text = str(raw or "").strip()
        if not text:
            return {}
        try:
            data = json.loads(text)
        except Exception:
            logger.warning("STT_REPLACE_JSON is invalid JSON; skip custom replacements")
            return {}
        if not isinstance(data, dict):
            return {}
        cleaned: dict[str, str] = {}
        for key, value in data.items():
            src = str(key or "").strip()
            dst = str(value or "").strip()
            if src and dst:
                cleaned[src] = dst
        return cleaned

    def _build_stt_prompt(self) -> str:
        """Собирает промпт для улучшения пунктуации и распознавания терминов."""
        base_prompt = (
            "Транскрибируй русскую речь точно, с корректной пунктуацией, "
            "заглавными буквами и абзацами по смыслу. "
            "Не добавляй лишних слов от себя."
        )
        if self.stt_hotwords:
            hotwords_block = ", ".join(self.stt_hotwords[:40])
            return f"{base_prompt} Важные термины: {hotwords_block}."
        return base_prompt

    def _build_primary_stt_kwargs(self) -> dict[str, Any]:
        """Расширенный профиль декодирования для лучшего качества текста."""
        return {
            "initial_prompt": self._build_stt_prompt(),
            "language": self.stt_language,
            "temperature": self.stt_temperature,
            "beam_size": self.stt_beam_size,
            "best_of": self.stt_best_of,
            "patience": self.stt_patience,
            "condition_on_previous_text": self.stt_condition_on_previous_text,
            "no_speech_threshold": self.stt_no_speech_threshold,
            "compression_ratio_threshold": self.stt_compression_ratio_threshold,
            "verbose": False,
        }

    def _build_fallback_stt_kwargs(self) -> dict[str, Any]:
        """Минимальный профиль, совместимый с более старыми версиями."""
        return {
            "initial_prompt": self._build_stt_prompt(),
            "language": self.stt_language,
            "temperature": self.stt_temperature,
            "verbose": False,
        }

    async def _run_mlx_transcribe_isolated(self, file_path: str) -> dict[str, Any]:
        """
        Запускает MLX Whisper в отдельном процессе.
        Это защищает основной процесс Krab от аварий Metal/AGX (SIGABRT).
        """
        payload = {
            "primary_kwargs": self._build_primary_stt_kwargs(),
            "fallback_kwargs": self._build_fallback_stt_kwargs(),
        }
        cmd = [
            sys.executable,
            "-m",
            "src.modules.perceptor_stt_worker",
            file_path,
            self.whisper_model,
            json.dumps(payload, ensure_ascii=False),
        ]

        try:
            completed = await asyncio.to_thread(
                subprocess.run,
                cmd,
                capture_output=True,
                text=True,
                timeout=max(30, self.stt_worker_timeout_seconds),
                check=False,
            )
        except subprocess.TimeoutExpired:
            return {"_worker_error": f"stt_worker_timeout:{self.stt_worker_timeout_seconds}s"}
        except Exception as exc:
            return {"_worker_error": f"stt_worker_spawn_failed:{exc}"}

        if completed.returncode != 0:
            stderr = (completed.stderr or "").strip()
            stdout = (completed.stdout or "").strip()
            reason = stderr or stdout or f"exit_code={completed.returncode}"
            return {"_worker_error": f"stt_worker_failed:{reason}"}

        output = (completed.stdout or "").strip()
        if not output:
            return {"_worker_error": "stt_worker_failed:empty_stdout"}
        last_line = output.splitlines()[-1]
        try:
            payload_obj = json.loads(last_line)
        except Exception:
            return {"_worker_error": f"stt_worker_failed:invalid_json:{last_line[:200]}"}
        if not isinstance(payload_obj, dict):
            return {"_worker_error": "stt_worker_failed:invalid_payload_type"}
        if payload_obj.get("ok") is False:
            return {"_worker_error": str(payload_obj.get("error", "stt_worker_failed:unknown"))}
        return {"text": str(payload_obj.get("text", "")).strip()}

    async def _run_mlx_transcribe_with_fallback(self, mlx_whisper: Any, file_path: str) -> dict[str, Any]:
        """Пробует расширенный STT-профиль, при несовместимости откатывается на базовый."""
        primary_kwargs = self._build_primary_stt_kwargs()
        try:
            return await asyncio.to_thread(
                mlx_whisper.transcribe,
                file_path,
                path_or_hf_repo=self.whisper_model,
                **primary_kwargs,
            )
        except TypeError as exc:
            logger.warning("mlx_whisper does not support full STT args, fallback to basic profile: %s", exc)
            return await asyncio.to_thread(
                mlx_whisper.transcribe,
                file_path,
                path_or_hf_repo=self.whisper_model,
                **self._build_fallback_stt_kwargs(),
            )

    def _apply_custom_replacements(self, text: str) -> str:
        """
        Применяет пользовательские коррекции (если задан STT_REPLACE_JSON).
        Заменяет по границам слов в регистронезависимом режиме.
        """
        if not self.stt_replace_map or not text:
            return text
        fixed = text
        for raw_src, raw_dst in self.stt_replace_map.items():
            src = re.escape(raw_src)
            fixed = re.sub(rf"(?<!\w){src}(?!\w)", raw_dst, fixed, flags=re.IGNORECASE)
        return fixed

    def _capitalize_sentences(self, text: str) -> str:
        """Поднимает первую букву в начале предложения."""
        if not text:
            return text
        chars = list(text)
        need_upper = True
        for idx, ch in enumerate(chars):
            if need_upper and ch.isalpha():
                chars[idx] = ch.upper()
                need_upper = False
            if ch in ".!?":
                need_upper = True
            elif not ch.isspace() and ch not in "\"'«»()[]{}":
                # Внутри слова/фразы верхний регистр не форсируем.
                need_upper = False
        return "".join(chars)

    def _postprocess_transcript(self, raw_text: str) -> str:
        """
        Детеминированная постобработка распознанного текста:
        - нормализация пробелов/пунктуации,
        - добавление завершающего знака,
        - капитализация предложений,
        - пользовательские замены терминов.
        """
        text = str(raw_text or "").strip()
        if not text:
            return ""

        # Для командных префиксов (!, /) пунктуацию не вмешиваем.
        if text.startswith(("!", "/")):
            return text

        text = re.sub(r"\s+", " ", text)
        text = re.sub(r"\s+([,.;:!?])", r"\1", text)
        text = re.sub(r"([,.;:!?])(?=[^\s\"')\]»}])", r"\1 ", text)
        text = re.sub(r"([!?.,])\1{2,}", r"\1", text)
        text = text.strip()

        if len(text.split()) >= 5 and text[-1] not in ".!?":
            text += "."

        text = self._capitalize_sentences(text)
        text = self._apply_custom_replacements(text)
        return text

    async def analyze_image(self, file_path: str, router, prompt: str) -> str:
        """
        Анализирует изображение. Автоматически конвертирует HEIC.
        """
        converted_path = file_path
        start_time = time.time()
        self.last_vision_meta = {
            "route": "unknown",
            "model": "",
            "fallback_used": False,
            "local_enabled": bool(self.local_vision_enabled),
            "error": "",
        }

        try:
            logger.info(f"📸 Starting Vision Analysis: {file_path}")
            # 1. Проверка формата и конвертация если нужно
            if str(file_path).lower().endswith(".heic"):
                img = Image.open(file_path)
                converted_path = f"{file_path}.jpg"
                img.save(converted_path, format="JPEG")
                logger.info(f"Converted HEIC to JPG: {converted_path}")

            # 2. Vision Request via Gemini SDK
            if self.local_vision_enabled:
                local_result = await self._analyze_image_local_lm_studio(
                    file_path=converted_path,
                    router=router,
                    prompt=prompt,
                )
                if local_result.get("ok"):
                    duration = time.time() - start_time
                    self.last_vision_meta = {
                        "route": "local_lm_studio",
                        "model": str(local_result.get("model") or ""),
                        "fallback_used": False,
                        "local_enabled": True,
                        "error": "",
                    }
                    logger.info(
                        "✅ Local Vision (LM Studio) success in %.2fs (model=%s)",
                        duration,
                        local_result.get("model", "-"),
                    )
                    return str(local_result.get("text", "")).strip()
                self.last_vision_meta = {
                    "route": "cloud_gemini",
                    "model": str(self.vision_model or ""),
                    "fallback_used": True,
                    "local_enabled": True,
                    "error": str(local_result.get("error") or ""),
                }
                logger.warning("⚠️ Local Vision failed, fallback to Gemini: %s", local_result.get("error"))

            if not _GENAI_AVAILABLE:
                logger.error("❌ Google GenAI SDK not found.")
                self.last_vision_meta = {
                    "route": "error",
                    "model": "",
                    "fallback_used": bool(self.local_vision_enabled),
                    "local_enabled": bool(self.local_vision_enabled),
                    "error": "google_genai_sdk_missing",
                }
                return "Ошибка: Google GenAI SDK не установлен."
                
            api_key = (router.gemini_key if hasattr(router, 'gemini_key') else None) or self.gemini_key
            if not api_key:
                logger.error("❌ Gemini API Key missing.")
                self.last_vision_meta = {
                    "route": "error",
                    "model": "",
                    "fallback_used": bool(self.local_vision_enabled),
                    "local_enabled": bool(self.local_vision_enabled),
                    "error": "gemini_api_key_missing",
                }
                return "Ошибка: Нет ключа Gemini API."

            # Инициализация клиента
            client = genai.Client(api_key=api_key)
            
            # Открываем изображение через PIL
            img_pil = Image.open(converted_path)
            
            logger.info(f"📡 Sending Vision Request to {self.vision_model}...")
            # Запускаем в потоке, так как SDK блокирующий
            response = await asyncio.to_thread(
                client.models.generate_content,
                model=self.vision_model,
                contents=[prompt, img_pil]
            )
            
            if response and response.text:
                 duration = time.time() - start_time
                 self.last_vision_meta = {
                     "route": "cloud_gemini",
                     "model": str(self.vision_model or ""),
                     "fallback_used": bool(self.local_vision_enabled),
                     "local_enabled": bool(self.local_vision_enabled),
                     "error": "",
                 }
                 logger.info(f"✅ Vision Success in {duration:.2f}s")
                 return response.text
            
            logger.warning("⚠️ Gemini returned empty text.")
            self.last_vision_meta = {
                "route": "cloud_gemini",
                "model": str(self.vision_model or ""),
                "fallback_used": bool(self.local_vision_enabled),
                "local_enabled": bool(self.local_vision_enabled),
                "error": "gemini_empty_response",
            }
            return "Не удалось проанализировать изображение (пустой ответ)."

        except Exception as e:
            logger.error(f"❌ Vision error: {e}", exc_info=True)
            self.last_vision_meta = {
                "route": "error",
                "model": "",
                "fallback_used": bool(self.local_vision_enabled),
                "local_enabled": bool(self.local_vision_enabled),
                "error": str(e),
            }
            return f"Я ослеп, По. Ошибка: {e}"
        finally:
            # Чистим конвертированный файл если он создавался
            if converted_path != file_path and os.path.exists(converted_path):
                try:
                    os.remove(converted_path)
                except Exception:
                    pass

    def get_last_vision_meta(self) -> Dict[str, Any]:
        """Возвращает фактический маршрут последнего vision-запроса."""
        return dict(self.last_vision_meta)

    async def analyze_visual(self, file_path: str, prompt: str) -> str:
        """
        Универсальный анализ изображений (включая скриншоты).
        """
        start_time = time.time()
        try:
            if not _GENAI_AVAILABLE:
                return "Ошибка: Google GenAI SDK не установлен."

            api_key = self.gemini_key
            if not api_key:
                return "Ошибка: Нет ключа Gemini API."

            client = genai.Client(api_key=api_key)
            img_pil = Image.open(file_path)
            
            logger.info(f"📡 Sending Visual Analysis request ({self.vision_model})...")
            response = await asyncio.to_thread(
                client.models.generate_content,
                model=self.vision_model,
                contents=[prompt, img_pil]
            )
            
            duration = time.time() - start_time
            if response and response.text:
                logger.info(f"✅ Visual Analysis success in {duration:.2f}s")
                return response.text
            
            return "Пустой ответ."

        except Exception as e:
            logger.error(f"❌ Visual analysis error: {e}", exc_info=True)
            return f"Ошибка зрения: {e}"

    def _resolve_local_vision_model(self, router) -> str:
        """
        Выбирает локальную vision-модель:
        1) LOCAL_VISION_MODEL
        2) active_local_model роутера
        3) LOCAL_PREFERRED_MODEL роутера
        """
        if self.local_vision_model:
            return self.local_vision_model

        active_model = str(getattr(router, "active_local_model", "") or "").strip()
        if active_model:
            return active_model

        preferred_model = str(getattr(router, "local_preferred_model", "") or "").strip()
        if preferred_model:
            return preferred_model

        return ""

    def _resolve_lm_studio_http_base(self, router) -> str:
        """
        Возвращает базовый HTTP URL LM Studio без суффиксов endpoint'ов.
        Поддерживает формы:
        - http://host:1234
        - http://host:1234/v1
        - ws://host:1234/v1/chat/completions
        """
        lm_raw = str(getattr(router, "lm_studio_url", "") or "").strip()
        if not lm_raw:
            lm_raw = str(os.getenv("LM_STUDIO_URL", "http://127.0.0.1:1234/v1")).strip()
        lm_raw = lm_raw.rstrip("/")
        if lm_raw.startswith("ws://"):
            lm_raw = "http://" + lm_raw[len("ws://") :]
        elif lm_raw.startswith("wss://"):
            lm_raw = "https://" + lm_raw[len("wss://") :]

        suffixes = (
            "/v1/chat/completions",
            "/chat/completions",
            "/api/v1",
            "/v1",
        )
        lowered = lm_raw.lower()
        for suffix in suffixes:
            if lowered.endswith(suffix):
                lm_raw = lm_raw[: -len(suffix)]
                lowered = lm_raw.lower()
        return lm_raw.rstrip("/")

    def _extract_model_entries(self, payload: Any) -> list[dict[str, Any]]:
        """Нормализует ответ каталога моделей LM Studio в список словарей."""
        if isinstance(payload, list):
            return [item for item in payload if isinstance(item, dict)]
        if not isinstance(payload, dict):
            return []

        for key in ("models", "data", "items", "result"):
            candidate = payload.get(key)
            if isinstance(candidate, list):
                return [item for item in candidate if isinstance(item, dict)]
        return []

    async def _collect_lm_studio_models(self, router) -> list[dict[str, Any]]:
        """
        Читает каталог моделей LM Studio.
        Если endpoint недоступен/формат неизвестен, возвращает пустой список.
        """
        base = self._resolve_lm_studio_http_base(router)
        if not base:
            return []
        endpoints = [
            f"{base}/api/v1/models",
            f"{base}/v1/models",
        ]
        timeout = aiohttp.ClientTimeout(total=6)
        for endpoint in endpoints:
            try:
                async with aiohttp.ClientSession(timeout=timeout) as session:
                    async with session.get(endpoint) as resp:
                        if resp.status != 200:
                            continue
                        payload = await resp.json(content_type=None)
                        entries = self._extract_model_entries(payload)
                        if entries:
                            return entries
            except Exception:
                continue
        return []

    def _find_model_entry(self, entries: list[dict[str, Any]], model_name: str) -> Optional[dict[str, Any]]:
        """Ищет запись модели по key/id/name/model в каталоге LM Studio."""
        target = str(model_name or "").strip().lower()
        if not target:
            return None
        for entry in entries:
            for key in ("key", "id", "model", "name"):
                candidate = str(entry.get(key) or "").strip().lower()
                if not candidate:
                    continue
                if candidate == target:
                    return entry
        for entry in entries:
            for key in ("key", "id", "model", "name"):
                candidate = str(entry.get(key) or "").strip().lower()
                if not candidate:
                    continue
                if target in candidate or candidate in target:
                    return entry
        return None

    def _infer_vision_support_from_entry(
        self,
        entry: Optional[dict[str, Any]],
        model_name: str,
    ) -> tuple[Optional[bool], str]:
        """
        Определяет поддержку vision.
        Возвращает (True|False|None, reason), где None = не удалось достоверно определить.
        """
        lower_name = str(model_name or "").strip().lower()
        explicit_true_tokens = {"vision", "image", "image_input", "multimodal", "vlm", "mm"}
        explicit_text_tokens = {"text", "text_only", "text-only"}

        # 1) Эвристика по имени (полезна, когда каталог бедный по метаданным).
        if any(token in lower_name for token in ("glm-4.6v", "glm-4v", "vision", "vlm", "llava", "qwen2-vl", "internvl", "minicpm-v", "phi-3.5-vision")):
            return True, "name_hint"

        if not isinstance(entry, dict):
            return None, "catalog_entry_missing"

        for key in ("vision", "supports_vision", "image_input", "multimodal"):
            if key in entry and isinstance(entry.get(key), bool):
                return bool(entry.get(key)), f"field:{key}"

        capabilities = entry.get("capabilities")
        if isinstance(capabilities, dict):
            for key in ("vision", "image", "image_input", "multimodal"):
                if key in capabilities and isinstance(capabilities.get(key), bool):
                    return bool(capabilities.get(key)), f"capability:{key}"
            normalized_keys = {str(k).strip().lower() for k in capabilities.keys()}
            if normalized_keys.intersection(explicit_true_tokens):
                return True, "capability_keys"

        def _normalize_tokens(value: Any) -> set[str]:
            if isinstance(value, str):
                return {token for token in re.split(r"[\s,;/|]+", value.strip().lower()) if token}
            if isinstance(value, list):
                tokens: set[str] = set()
                for item in value:
                    if isinstance(item, str):
                        tokens.update(_normalize_tokens(item))
                    elif isinstance(item, dict):
                        for item_key in ("name", "id", "type", "kind"):
                            raw = item.get(item_key)
                            if isinstance(raw, str):
                                tokens.update(_normalize_tokens(raw))
                return tokens
            return set()

        modality_tokens = _normalize_tokens(entry.get("modalities")) | _normalize_tokens(entry.get("modality"))
        capability_tokens = _normalize_tokens(capabilities)
        domain_tokens = _normalize_tokens(entry.get("domain")) | _normalize_tokens(entry.get("type"))
        all_tokens = modality_tokens | capability_tokens | domain_tokens

        if all_tokens.intersection(explicit_true_tokens):
            return True, "token_hint"
        if all_tokens and all_tokens.issubset(explicit_text_tokens):
            return False, "text_only_tokens"

        return None, "unknown_capabilities"

    async def _check_local_vision_support(self, router, model_name: str) -> dict[str, Any]:
        """
        Проверяет, поддерживает ли выбранная модель local vision.
        supported:
        - True  -> модель явно поддерживает vision
        - False -> модель явно text-only
        - None  -> не удалось определить (продолжаем попытку запроса)
        """
        entries = await self._collect_lm_studio_models(router)
        entry = self._find_model_entry(entries, model_name)
        supported, reason = self._infer_vision_support_from_entry(entry, model_name)
        return {
            "supported": supported,
            "reason": reason,
            "model": model_name,
            "catalog_entries": len(entries),
            "entry_found": bool(entry),
        }

    def _build_image_data_url(self, file_path: str) -> str:
        """Кодирует файл изображения в data-url для OpenAI-compatible API LM Studio."""
        mime_type = mimetypes.guess_type(file_path)[0] or "image/jpeg"
        image_bytes = Path(file_path).read_bytes()
        encoded = base64.b64encode(image_bytes).decode("ascii")
        return f"data:{mime_type};base64,{encoded}"

    def _extract_lm_studio_vision_text(self, payload: Dict[str, Any]) -> str:
        """Извлекает текст ответа из разных форматов message.content."""
        choices = payload.get("choices") if isinstance(payload, dict) else None
        if not isinstance(choices, list) or not choices:
            return ""
        message = choices[0].get("message", {}) if isinstance(choices[0], dict) else {}
        content = message.get("content")
        if isinstance(content, str):
            return content.strip()
        if isinstance(content, list):
            parts: list[str] = []
            for item in content:
                if not isinstance(item, dict):
                    continue
                if item.get("type") == "text":
                    text = str(item.get("text", "")).strip()
                    if text:
                        parts.append(text)
            return "\n".join(parts).strip()
        return ""

    async def _analyze_image_local_lm_studio(self, file_path: str, router, prompt: str) -> Dict[str, Any]:
        """
        Локальный vision-запрос в LM Studio через OpenAI-compatible /chat/completions.
        Возвращает {"ok": bool, "text": "...", "error": "...", "model": "..."}.
        """
        model_name = self._resolve_local_vision_model(router)
        if not model_name:
            return {"ok": False, "error": "local_vision_model_not_set", "model": ""}

        precheck = await self._check_local_vision_support(router, model_name)
        if precheck.get("supported") is False:
            return {
                "ok": False,
                "error": f"local_model_not_vision_capability:{precheck.get('reason', 'text_only')}",
                "model": model_name,
                "precheck": precheck,
            }

        lm_base = self._resolve_lm_studio_http_base(router)
        if not lm_base:
            return {"ok": False, "error": "lmstudio_base_url_missing", "model": model_name}
        chat_url = f"{lm_base}/v1/chat/completions"

        data_url = self._build_image_data_url(file_path)
        payload = {
            "model": model_name,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {"type": "image_url", "image_url": {"url": data_url}},
                    ],
                }
            ],
            "temperature": 0.2,
            "max_tokens": max(200, int(self.local_vision_max_tokens)),
        }

        timeout = aiohttp.ClientTimeout(total=max(10, int(self.local_vision_timeout_seconds)))
        try:
            async with aiohttp.ClientSession(timeout=timeout) as session:
                async with session.post(chat_url, json=payload) as resp:
                    if resp.status != 200:
                        body = await resp.text()
                        return {
                            "ok": False,
                            "error": f"lmstudio_http_{resp.status}:{body[:240]}",
                            "model": model_name,
                            "precheck": precheck,
                        }
                    data = await resp.json()
        except Exception as exc:
            return {
                "ok": False,
                "error": f"lmstudio_vision_request_failed:{exc}",
                "model": model_name,
                "precheck": precheck,
            }

        text = self._extract_lm_studio_vision_text(data)
        if not text:
            return {
                "ok": False,
                "error": "lmstudio_vision_empty_response",
                "model": model_name,
                "precheck": precheck,
            }
        return {"ok": True, "text": text, "model": model_name, "precheck": precheck}

    async def analyze_video(self, file_path: str, router, prompt: str) -> str:
        """
        Анализирует видео-сообщение (включая кружки) через Gemini 2.0 Flash.
        """
        try:
            if not _GENAI_AVAILABLE:
                return "Ошибка: Google GenAI SDK не установлен."

            api_key = router.gemini_key or self.gemini_key
            if not api_key:
                return "Ошибка: Нет ключа Gemini API для анализа видео."

            client = genai.Client(api_key=api_key)
            
            logger.info(f"🎞️ Uploading video to Gemini: {file_path}")
            
            # Загружаем файл
            video_file = await asyncio.to_thread(
                client.files.upload,
                path=file_path
            )
            
            # Ждем обработки
            while True:
                # Polling file status
                # Using to_thread because client methods might be blocking
                file_info = await asyncio.to_thread(client.files.get, name=video_file.name)
                
                # Check status (Assuming 'ACTIVE' or 'PROCESSING')
                # In new SDK, state is an enum or string.
                state = str(file_info.state)
                
                if "ACTIVE" in state:
                    break
                elif "FAILED" in state:
                    raise Exception("Google Video Processing failed.")
                
                logger.info(f"Video processing... {state}")
                await asyncio.sleep(2)

            logger.info(f"✅ Video processing complete: {video_file.name}")
            
            response = await asyncio.to_thread(
                client.models.generate_content,
                model=self.vision_model,
                contents=[prompt, video_file]
            )
            
            # Удаляем файл
            await asyncio.to_thread(client.files.delete, name=video_file.name)
            
            return response.text if response else "Пустой ответ по видео."

        except Exception as e:
            logger.error(f"Video analysis error: {e}")
            return f"Не удалось посмотреть видео: {e}"

    async def analyze_document(self, file_path: str, router, prompt: str) -> str:
        """
        Анализирует документ (PDF) через Gemini Native Document Understanding.
        """
        try:
            if not _GENAI_AVAILABLE:
                return "Ошибка: Google GenAI SDK не установлен."

            api_key = router.gemini_key or self.gemini_key
            if not api_key:
                return "Ошибка: Нет ключа Gemini API для анализа документа."

            client = genai.Client(api_key=api_key)
            
            logger.info(f"📄 Uploading document to Gemini: {file_path}")
            
            # Загружаем файл
            doc_file = await asyncio.to_thread(
                client.files.upload,
                path=file_path
            )
            
            # Ждем обработки
            while True:
                file_info = await asyncio.to_thread(client.files.get, name=doc_file.name)
                state = str(file_info.state)
                
                if "ACTIVE" in state:
                    break
                elif "FAILED" in state:
                    raise Exception("Google Document Processing failed.")
                
                logger.info(f"Document processing... {state}")
                await asyncio.sleep(2)

            logger.info(f"✅ Document processing complete: {doc_file.name}")
            
            response = await asyncio.to_thread(
                client.models.generate_content,
                model=self.vision_model,
                contents=[prompt, doc_file]
            )
            
            # Удаляем файл из облака
            await asyncio.to_thread(client.files.delete, name=doc_file.name)
            
            return response.text if response else "Пустой ответ по документу."

        except Exception as e:
            logger.error(f"Document analysis error: {e}")
            return f"Не удалось проанализировать документ: {e}"

    def _clean_text_for_tts(self, text: str) -> str:
        """
        Очищает текст от технических тегов и лишней разметки перед озвучкой.
        """
        import re
        # Удаляем теги коробок и мыслительные блоки
        text = re.sub(r'<\|begin_of_box\|>|<\|end_of_box\|>', '', text)
        text = re.sub(r'<\|thought\|>.*?</\|thought\|>', '', text, flags=re.DOTALL)
        # Удаляем лишние спецсимволы, оставляя знаки препинания
        text = re.sub(r'[^\w\s\.\,\!\?\-\:\(\)]', '', text)
        text = re.sub(r'http\S+', '', text)
        # Удаляем лишние пробелы и пустые строки
        text = re.sub(r'\s+', ' ', text).strip()
        return text

    async def speak(self, text: str, voice: str = "ru-RU-SvetlanaNeural", method: str = "auto") -> str:
        """
        Генерирует голосовое сообщение (TTS).
        Поддерживает edge-tts (бесплатно) и OpenAI (платно, качественнее).
        Возвращает путь к .ogg файлу.
        """
        file_id = str(uuid.uuid4())
        os.makedirs("artifacts/downloads", exist_ok=True)
        
        mp3_path = f"artifacts/downloads/{file_id}.mp3"
        ogg_path = f"artifacts/downloads/{file_id}.ogg"
        
        # Очищаем текст перед озвучкой
        clean_text = self._clean_text_for_tts(text)
        if not clean_text:
            logger.warning("TTS text is empty after cleaning. Skipping speech synthesis.")
            return None

        # 1. Выбор метода
        use_openai = False
        if method == "openai":
            use_openai = True
        elif method == "auto":
            # В будущем тут можно добавить логику выбора
            pass

        try:
            if use_openai:
                return await self._speak_openai(clean_text, mp3_path, ogg_path)
            
            # Попытка через edge-tts
            res = await self._speak_edge(clean_text, voice, mp3_path, ogg_path)
            if res:
                return res
            
            # Fallback на openai если edge-tts упал
            logger.warning("⚠️ edge-tts failed, falling back to OpenAI TTS...")
            return await self._speak_openai(clean_text, mp3_path, ogg_path)

        except Exception as e:
            logger.error(f"TTS Master Error: {e}")
            return None

    async def _speak_edge(self, text: str, voice: str, mp3_path: str, ogg_path: str) -> Optional[str]:
        """Озвучка через бесплатный edge-tts."""
        try:
            # Если голос не указан или стандартный от macOS, меняем на качественный
            if voice in ["Milena", "Yuri", "Katya", "default"]:
                voice = "ru-RU-SvetlanaNeural"

            logger.info(f"🗣️ Speaking via edge-tts: {text[:40]}... (Voice: {voice})")
            communicate = edge_tts.Communicate(text, voice)
            await communicate.save(mp3_path)

            if not os.path.exists(mp3_path) or os.path.getsize(mp3_path) < 100:
                return None
            
            return await self._convert_to_ogg(mp3_path, ogg_path)
        except Exception as e:
            logger.error(f"edge-tts error: {e}")
            return None

    async def _speak_openai(self, text: str, mp3_path: str, ogg_path: str) -> Optional[str]:
        """Озвучка через платный OpenAI API."""
        try:
            from openai import AsyncOpenAI
            api_key = os.getenv("OPENAI_API_KEY") or self.gemini_key # Иногда ключи совместимы в шлюзах
            if not api_key or "sk-" not in api_key:
                logger.error("❌ OpenAI API Key missing for TTS fallback.")
                return None

            logger.info(f"🎙️ Speaking via OpenAI TTS: {text[:40]}...")
            client = AsyncOpenAI(api_key=api_key)
            
            # Используем модель tts-1 (быстрая) и голос nova/shimmer
            response = await client.audio.speech.create(
                model="tts-1",
                voice="nova",
                input=text
            )
            await asyncio.to_thread(response.stream_to_file, mp3_path)
            
            return await self._convert_to_ogg(mp3_path, ogg_path)
        except Exception as e:
            logger.error(f"OpenAI TTS error: {e}")
            return None

    async def _convert_to_ogg(self, mp3_path: str, ogg_path: str) -> Optional[str]:
        """Конвертация MP3 -> OGG Opus через ffmpeg."""
        try:
            proc_ffmpeg = await asyncio.create_subprocess_exec(
                "ffmpeg", "-i", mp3_path, "-c:a", "libopus", "-b:a", "24k", "-vbr", "on", "-y", ogg_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            await proc_ffmpeg.communicate()
            
            if os.path.exists(mp3_path):
                os.remove(mp3_path)
            
            if os.path.exists(ogg_path) and os.path.getsize(ogg_path) > 200:
                logger.info(f"✅ TTS Generated: {ogg_path}")
                return ogg_path
            return None
        except Exception as e:
            logger.error(f"FFmpeg error: {e}")
            return None
