# -*- coding: utf-8 -*-
"""Multimodal Module

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nwK0xjjNETf0WZaRHpDGGjPzDs4reBf
"""

# -*- coding: utf-8 -*-
"""
Perceptor Module (Eyes & Ears).
Отвечает за транскрибацию аудио и анализ изображений.
Умеет конвертировать HEIC -> JPG на лету.
"""

import os
import logging
from typing import Dict, Any
from io import BytesIO
from PIL import Image
from pillow_heif import register_heif_opener
from pathlib import Path

# Регистрируем поддержку HEIC для Pillow
register_heif_opener()

logger = logging.getLogger(__name__)

class Perceptor:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        # M4 Max Optimization: Use mlx-community/whisper-large-v3-turbo
        self.whisper_model = "mlx-community/whisper-large-v3-turbo"
        logger.info(f"👂 Perceptor initialized. Audio Model: {self.whisper_model}")
        
        # Warmup MLX
        self._warmup_audio()

    def _warmup_audio(self):
        """Прогрев Neural Engine для MLX Whisper."""
        try:
            import mlx_whisper
            import numpy as np
            logger.info("🔥 Warming up Neural Engine (MLX)...")
            # Прогрев тишиной
            mlx_whisper.transcribe(np.zeros(16000, dtype=np.float32), path_or_hf_repo=self.whisper_model)
            logger.info("✅ MLX Audio Model Ready.")
        except Exception as e:
            logger.warning(f"MLX Warmup Skipped: {e}")

    async def transcribe(self, file_path: str, router) -> str:
        """
        Транскрибирует аудио с помощью MLX Whisper (Local).
        """
        try:
            logger.info(f"🎤 Transcribing: {file_path}")
            import mlx_whisper
            import time

            start_time = time.time()
            
            # Используем модель из конфига/инита
            # Промпт-подсказка для Whisper (улучшает пунктуацию и точность)
            # Взято из KrabEar v4.7 (проверенная конфигурация)
            punctuation_prompt = "Привет, я транскрибирую этот текст с правильной пунктуацией, заглавными буквами и форматированием."
            
            result = mlx_whisper.transcribe(
                file_path, 
                path_or_hf_repo=self.whisper_model,
                initial_prompt=punctuation_prompt,
                language="ru",       # Форсируем русский
                temperature=0.0,     # Убираем галлюцинации
                verbose=False
            )
            
            text = result.get("text", "").strip()
            duration = time.time() - start_time
            
            logger.info(f"✅ Transcribed in {duration:.2f}s: {text[:50]}...")
            return text

        except Exception as e:
            logger.error(f"❌ Local Transcription Failed: {e}")
            return f"Ошибка транскрибации: {e}"

    async def analyze_image(self, file_path: str, router, prompt: str) -> str:
        """
        Анализирует изображение. Автоматически конвертирует HEIC.
        """
        converted_path = file_path

        try:
            # 1. Проверка формата и конвертация если нужно
            if str(file_path).lower().endswith(".heic"):
                img = Image.open(file_path)
                converted_path = f"{file_path}.jpg"
                img.save(converted_path, format="JPEG")
                logger.info(f"Converted HEIC to JPG: {converted_path}")

            # 2. Отправка в Роутер (Vision Request)
            # Vision задачи лучше всего решает Cloud Gemini (Pro Vision) или LLaVA (Local)
            # Передаем в router путь к картинке

            # ВНИМАНИЕ: Здесь router должен уметь принимать image_path.
            # Мы вызываем метод router.route_query с типом 'vision'
            # (Этот тип нужно добавить в router, пока используем chat заглушку)

            # Временная реализация через Gemini напрямую (так как Router в процессе доработки)
            import google.generativeai as genai

            if not router.gemini_key:
                return "Ошибка: Нет ключа Gemini API."

            genai.configure(api_key=router.gemini_key)
            model = genai.GenerativeModel('gemini-2.0-flash') # Vision model

            cookie_picture = Image.open(converted_path)
            response = model.generate_content([prompt, cookie_picture])
            return response.text

        except Exception as e:
            logger.error(f"Vision error: {e}")
            return f"Я ослеп, По. Ошибка: {e}"
        finally:
            # Чистим конвертированный файл если он создавался
            if converted_path != file_path and os.path.exists(converted_path):
                os.remove(converted_path)

    async def speak(self, text: str, voice: str = "Milena") -> str:
        """
        Генерирует голосовое сообщение (TTS) через macOS 'say' + ffmpeg.
        Возвращает путь к .ogg файлу.
        """
        import asyncio
        import uuid
        
        file_id = str(uuid.uuid4())
        # Ensure dir exists
        os.makedirs("artifacts/downloads", exist_ok=True)
        
        aiff_path = f"artifacts/downloads/{file_id}.aiff"
        ogg_path = f"artifacts/downloads/{file_id}.ogg"
        
        try:
            logger.info(f"🗣️ Speaking: {text[:30]}... (Voice: {voice})")
            
            # 1. Generate AIFF
            proc_say = await asyncio.create_subprocess_exec(
                "say", "-v", voice, "-o", aiff_path, text,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await proc_say.communicate()

            if proc_say.returncode != 0:
                logger.error(f"TTS (say) failed: {stderr.decode().strip()}")
                return None
            
            if not os.path.exists(aiff_path):
                logger.error(f"TTS (say) completed but file missing: {aiff_path}")
                return None
            
            # 2. Convert to OGG (Voice Note format)
            proc_ffmpeg = await asyncio.create_subprocess_exec(
                "ffmpeg", "-i", aiff_path, "-c:a", "libopus", "-b:a", "24k", "-y", ogg_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await proc_ffmpeg.communicate()
            
            if proc_ffmpeg.returncode != 0:
                 logger.error(f"ffmpeg conversion failed: {stderr.decode().strip()}")
                 # Don't return None yet, maybe AIFF is useful? No, Telegram needs OGG/MP3 for voice usually.
                 return None

            if os.path.exists(aiff_path):
                 os.remove(aiff_path)
            
            if os.path.exists(ogg_path):
                logger.info(f"✅ TTS Generated: {ogg_path}")
                return ogg_path
            return None
            
        except Exception as e:
            logger.error(f"TTS Error: {e}")
            return None