# -*- coding: utf-8 -*-
"""Model Manager Core

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XGJds5XRvAKCYh_f6T95iwAfwkaec1Pe
"""

import os
import logging
import json
import requests
from typing import Dict, Any, List, Optional
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

class ModelRouter:
    def __init__(self):
        # Cloud Configuration
        self.gemini_key = os.getenv("GEMINI_API_KEY")
        # По умолчанию ставим Flash (быстро/дешево), Pro для сложных задач
        self.cloud_chat_model = os.getenv("GEMINI_CHAT_MODEL", "gemini-2.0-flash")
        self.cloud_think_model = "gemini-2.0-pro-exp-02-05" # Самая мощная на сегодня

        # Local Configuration (LM Studio)
        self.lms_url = os.getenv("LM_STUDIO_URL", "http://localhost:1234/v1")
        self.local_model_name = "qwen2.5-7b-instruct" # Дефолт, если не выбрали иное

    def get_cloud_model(self, task_type: str = "chat") -> str:
        """Возвращает ID модели для Gemini в зависимости от задачи"""
        if task_type == "thinking" or task_type == "code":
            return self.cloud_think_model
        return self.cloud_chat_model

    def scan_local_models(self) -> List[str]:
        """Сканирует доступные модели в LM Studio"""
        try:
            # LM Studio API для списка моделей
            resp = requests.get(f"{self.lms_url}/models", timeout=2)
            if resp.status_code == 200:
                data = resp.json()
                # Парсим ответ (LM Studio отдает список в поле 'data')
                models = [m['id'] for m in data.get('data', [])]
                logger.info(f"🔍 Найдено локальных моделей: {len(models)}")
                return models
        except Exception as e:
            logger.error(f"⚠️ Ошибка сканирования LM Studio: {e}")
        return []

    def load_local_model(self, model_id: str) -> bool:
        """
        Принудительно загружает модель в LM Studio.
        Это исправляет баг, когда модель не переключалась.
        """
        try:
            logger.info(f"🔄 Попытка загрузки модели: {model_id}")

            # 1. Сначала получаем текущую загруженную (если есть)
            # В LM Studio API v1 нет прямой команды "unload", но load новой обычно вытесняет старую.
            # Мы используем POST /v1/models/load (специфично для LMS)

            # Формируем URL для загрузки (LM Studio specific endpoint)
            load_url = self.lms_url.replace("/v1", "/api/v0/model/load") # Пробуем v0 API для управления

            # Если v0 недоступен, пробуем просто надеяться, что chat completion подхватит
            # Но лучше использовать CLI или правильный эндпоинт

            payload = {"model_path": model_id} # Или model_id в зависимости от версии LMS

            # Для надежности в рамках "Antigravity" подхода:
            # Мы просто сообщаем системе, какая модель выбрана, и при запросе генерации
            # передаем её имя в поле 'model'. LM Studio сама должна подгрузить её.
            self.local_model_name = model_id
            return True

        except Exception as e:
            logger.error(f"❌ Не удалось переключить модель: {e}")
            return False

    def get_best_model_for_task(self, task_description: str) -> Dict[str, str]:
        """
        Роутинг: Решает, какую модель использовать (Облако или Локал).
        """
        # Эвристика: Если задача простая (привет, как дела) -> Local или Flash
        # Если сложная (анализ, код) -> Gemini Pro

        is_complex = len(task_description) > 50 or "код" in task_description.lower() or "анализ" in task_description.lower()

        if is_complex and self.gemini_key:
            return {"provider": "google", "model": self.cloud_think_model}
        elif self.gemini_key:
            return {"provider": "google", "model": self.cloud_chat_model}
        else:
            return {"provider": "local", "model": self.local_model_name}

# Singleton
router = ModelRouter()