# -*- coding: utf-8 -*-
"""Swarm Manager

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zyiNzb4ID2C2df44gyszz9JDwUgV0lS_
"""

import logging
import importlib.util
import os
from typing import Dict, Any

logger = logging.getLogger(__name__)

class SwarmManager:
    """
    Менеджер для управления роями агентов (CrewAI / Native).
    Позволяет запускать команды (Trading, Dev, OSINT) одной строкой.
    """

    def __init__(self, swarm_dir: str = "src/swarm_definitions"):
        self.swarm_dir = swarm_dir
        self.available_swarms = {}
        self._scan_swarms()

    def _scan_swarms(self):
        """Сканирует папку на наличие определений роев"""
        if not os.path.exists(self.swarm_dir):
            os.makedirs(self.swarm_dir, exist_ok=True)

        for filename in os.listdir(self.swarm_dir):
            if filename.endswith("_team.py") or filename.endswith("_swarm.py"):
                name = filename.replace(".py", "")
                self.available_swarms[name] = os.path.join(self.swarm_dir, filename)

    def list_swarms(self) -> str:
        if not self.available_swarms:
            return "Нет доступных роев. Добавьте файлы в src/swarm_definitions/"
        return "\n".join([f"- {name}" for name in self.available_swarms.keys()])

    def run_swarm(self, swarm_name: str, input_data: str) -> str:
        """Динамически загружает и запускает рой"""
        if swarm_name not in self.available_swarms:
            return f"❌ Рой '{swarm_name}' не найден."

        file_path = self.available_swarms[swarm_name]

        try:
            # Динамический импорт модуля
            spec = importlib.util.spec_from_file_location(swarm_name, file_path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            # Ищем функцию запуска (обычно run_X)
            # Ожидаем, что в файле есть функция run(input_str)
            if hasattr(module, "run"):
                logger.info(f"🚀 Запуск роя {swarm_name}...")
                return module.run(input_data)
            else:
                return f"❌ В файле {swarm_name} нет функции 'run(input)'."

        except Exception as e:
            logger.error(f"Swarm Error: {e}")
            return f"Ошибка при запуске роя: {e}"