# -*- coding: utf-8 -*-
"""Trading Swarm Definition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NslsKy6Nblx9q_TtlENYATNZH2XrIj3g
"""

from crewai import Agent, Task, Crew, Process
import os

# Этот файл автоматически подхватится SwarmManager'ом

def run(market_context: str):
    """
    Точка входа для запуска торгового роя.
    """

    # 1. Аналитик
    analyst = Agent(
        role='Crypto Analyst',
        goal='Анализ рынка и поиск паттернов',
        backstory='Ты опытный трейдер, используешь тех. анализ.',
        verbose=True,
        allow_delegation=False
    )

    # 2. Риск-менеджер
    risk = Agent(
        role='Risk Manager',
        goal='Защита депозита',
        backstory='Ты параноик. Твоя задача - не дать слить депозит.',
        verbose=True,
        allow_delegation=False
    )

    # Задачи
    t1 = Task(
        description=f'Проанализируй ситуацию: {market_context}. Дай прогноз.',
        agent=analyst,
        expected_output="Аналитический отчет"
    )

    t2 = Task(
        description='На основе отчета рассчитай риск и размер позиции (или запрети сделку).',
        agent=risk,
        expected_output="Торговое решение (JSON)"
    )

    crew = Crew(
        agents=[analyst, risk],
        tasks=[t1, t2],
        process=Process.sequential
    )

    return crew.kickoff()