# -*- coding: utf-8 -*-
"""Trading Team

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJCwjpaW2Pu6Ib7HZHGS0nV2NprflM_n
"""

from crewai import Agent, Task, Crew, Process

def run_trading_swarm(market_data_context):
    """
    Запускает команду торговых агентов.
    Аргумент: market_data_context (строка с данными о рынке).
    """

    # 1. Агент: Аналитик Данных
    analyst = Agent(
        role='Senior Data Analyst',
        goal='Собрать и структурировать объективные данные о текущем состоянии рынка (технический анализ и сентимент).',
        backstory='''Ты хладнокровный аналитик. Твоя задача — без эмоций собирать факты.
        Ты анализируешь тренды, уровни поддержки/сопротивления, RSI, MACD.
        Ты никогда не даешь советов по покупке/продаже, ты только поставляешь чистые цифры.''',
        verbose=True,
        allow_delegation=False
    )

    # 2. Агент: Квант-Стратег
    strategist = Agent(
        role='Quant Trading Strategist',
        goal='Сгенерировать торговую гипотезу (Long/Short/Hold) на основе данных.',
        backstory='''Ты гениальный стратег хедж-фонда. Твоя задача — находить неэффективности рынка.
        Ты получаешь сухие данные от Аналитика и превращаешь их в торговую идею.
        Формат ответа: Направление, Точка входа, Обоснование.''',
        verbose=True,
        allow_delegation=False
    )

    # 3. Агент: Риск-Менеджер (Самый важный)
    risk_manager = Agent(
        role='Strict Risk Manager',
        goal='Оценить риски. Отклонить сделку или рассчитать Stop-Loss/Take-Profit.',
        backstory='''Ты параноидальный риск-менеджер. Твоя главная цель — ЗАЩИТИТЬ ДЕПОЗИТ.
        Правила:
        1. Риск на сделку макс 2%.
        2. Risk/Reward минимум 1:3.
        3. Если рынок непонятен — ставь ВЕТО (HOLD).
        Если одобряешь, выдай: Entry, SL, TP, Size.''',
        verbose=True,
        allow_delegation=False
    )

    # 4. Агент: Исполнитель (Paper Trader)
    paper_trader = Agent(
        role='Paper Trading Executor',
        goal='Зафиксировать сделку в формате JSON.',
        backstory='''Ты точный исполнитель. Ты берешь данные от Риск-менеджера и формируешь финальный JSON ордер
        для записи в базу данных или лог файл.''',
        verbose=True,
        allow_delegation=False
    )

    # Задачи
    task_analyze = Task(
        description=f'Проанализируй входящие данные рынка: "{market_data_context}". Выдели главные метрики.',
        expected_output='Структурированный отчет по рынку.',
        agent=analyst
    )

    task_strategy = Task(
        description='На основе отчета аналитика предложи сделку. Если сигнал слабый — рекомендуй HOLD.',
        expected_output='Торговый сигнал с аргументацией.',
        agent=strategist
    )

    task_risk = Task(
        description='Оцени сигнал. Если риск высок — запрети сделку. Иначе рассчитай параметры ордера (SL/TP). Депозит $10,000.',
        expected_output='Вердикт (ОДОБРЕНО/ОТКЛОНЕНО) и параметры.',
        agent=risk_manager
    )

    task_execute = Task(
        description='Сформируй финальный JSON объект сделки (или причину отказа).',
        expected_output='JSON строка.',
        agent=paper_trader
    )

    # Сборка команды
    crew = Crew(
        agents=[analyst, strategist, risk_manager, paper_trader],
        tasks=[task_analyze, task_strategy, task_risk, task_execute],
        process=Process.sequential
    )

    return crew.kickoff()