# Telegram command handlers (Фаза 4.4: вынос из userbot_bridge)
from .command_handlers import (
    handle_agent,
    handle_clear,
    handle_config,
    handle_diagnose,
    handle_help,
    handle_model,
    handle_panel,
    handle_read,
    handle_remember,
    handle_restart,
    handle_recall,
    handle_role,
    handle_search,
    handle_set,
    handle_status,
    handle_sysinfo,
    handle_voice,
    handle_web,
    handle_write,
    handle_ls,
)

__all__ = [
    "handle_agent",
    "handle_clear",
    "handle_config",
    "handle_diagnose",
    "handle_help",
    "handle_model",
    "handle_panel",
    "handle_read",
    "handle_remember",
    "handle_restart",
    "handle_recall",
    "handle_role",
    "handle_search",
    "handle_set",
    "handle_status",
    "handle_sysinfo",
    "handle_voice",
    "handle_web",
    "handle_write",
    "handle_ls",
]
