# -*- coding: utf-8 -*-
"""Content Team

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/163HuYC611d4jcOS6_Hd9Ht0y1NCdtj4_
"""

from crewai import Agent, Task, Crew, Process

def run_content_factory(topic):
    """
    Запускает команду создания контента.
    Аргумент: topic (тема статьи).
    """

    # 1. SEO Аналитик
    trend_analyst = Agent(
        role='SEO & Trend Analyst',
        goal='Найти лучшие ключевые слова и боли аудитории.',
        backstory='''Ты эксперт по трафику. Ты знаешь, что ищут люди.
        Ты составляешь семантическое ядро и структуру заголовков.''',
        verbose=True
    )

    # 2. Копирайтер
    copywriter = Agent(
        role='Creative Copywriter',
        goal='Написать вовлекающий текст на основе SEO-плана.',
        backstory='''Ты пишешь живым языком. Никакой воды. Ты используешь сторителлинг.
        Твоя задача — удержать читателя до последней строчки.''',
        verbose=True
    )

    # 3. Редактор
    editor = Agent(
        role='Chief Editor',
        goal='Проверить факты, стиль и отформатировать в Markdown.',
        backstory='''Ты строгий редактор. Ты исправляешь ошибки, убираешь лишнее и
        форматируешь текст (заголовки, списки, жирный шрифт) для публикации.''',
        verbose=True
    )

    # Задачи
    t1 = Task(
        description=f'Проведи исследование темы: "{topic}". Собери LSI-ключи.',
        expected_output='Список ключей и план статьи.',
        agent=trend_analyst
    )

    t2 = Task(
        description='Напиши полный черновик статьи по плану.',
        expected_output='Текст статьи.',
        agent=copywriter
    )

    t3 = Task(
        description='Отредактируй текст, добавь Markdown разметку и подготовь к релизу.',
        expected_output='Финальный файл статьи в формате Markdown.',
        agent=editor
    )

    crew = Crew(
        agents=[trend_analyst, copywriter, editor],
        tasks=[t1, t2, t3],
        process=Process.sequential
    )

    return crew.kickoff()