# -*- coding: utf-8 -*-
"""Dev Team

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAIG3pDAdI0KislEd_5Kn-wIwI3ARid-
"""

from crewai import Agent, Task, Crew, Process

def run_dev_squad(project_idea):
    """
    Запускает команду разработки с критиком.
    Аргумент: project_idea (описание проекта).
    """

    # 1. Архитектор
    architect = Agent(
        role='Senior System Architect',
        goal='Спроектировать надежную, масштабируемую архитектуру.',
        backstory='''Ты опытный архитектор. Ты любишь микросервисы, но только там, где они нужны.
        Твоя задача — превратить идею в технический план (Стек, БД, API).''',
        verbose=True
    )

    # 2. Разработчик
    coder = Agent(
        role='Lead Fullstack Developer',
        goal='Написать рабочий код по спецификации архитектора.',
        backstory='''Ты пишешь чистый Python/JS код. Ты следуешь принципам DRY и KISS.
        Ты реализуешь основную логику и структуру проекта.''',
        verbose=True
    )

    # 3. Злой Критик (QA & Security)
    angry_critic = Agent(
        role='Senior QA & Security Auditor',
        goal='Найти уязвимости и заставить переписать плохой код.',
        backstory='''Ты — "Злой Полицейский" в команде. Ты ненавидишь баги, утечки памяти и дыры в безопасности.
        Ты проверяешь код разработчика. Если находишь проблему — жестко критикуешь и требуешь исправления.
        Твой вердикт должен быть финальным: либо список правок, либо "ОДОБРЕНО".''',
        verbose=True
    )

    # Задачи
    t1 = Task(
        description=f'Разработай архитектуру для: "{project_idea}". Выбери стек и БД.',
        expected_output='Технический дизайн-документ (Markdown).',
        agent=architect
    )

    t2 = Task(
        description='На основе архитектуры напиши основной код (скелет приложения).',
        expected_output='Блоки кода с комментариями.',
        agent=coder
    )

    t3 = Task(
        description='Проведи аудит кода. Найди уязвимости. Если код плохой — напиши разгромный отзыв.',
        expected_output='Отчет об аудите безопасности и качества кода.',
        agent=angry_critic
    )

    crew = Crew(
        agents=[architect, coder, angry_critic],
        tasks=[t1, t2, t3],
        process=Process.sequential
    )

    return crew.kickoff()