# -*- coding: utf-8 -*-
"""Launcher

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XD07VLkp7veJfVc_JRTPaT4Z_ZLh9Y5R
"""

import os
from trading_swarm import run_trading_swarm
from dev_squad import run_dev_squad
from content_factory import run_content_factory
from osint_research import run_osint_research

# ==========================================
# ГЛАВНЫЙ ФАЙЛ ЗАПУСКА (LAUNCHER)
# ==========================================
# Инструкция:
# 1. Установите зависимости: pip install -r requirements.txt
# 2. Установите API ключ: export OPENAI_API_KEY='sk-...' (или в .env файле)
# 3. Запустите этот файл: python main.py

def main():
    print("==========================================")
    print("🤖 OPENCLAW AGENT SWARM LAUNCHER 🤖")
    print("==========================================")
    print("Выберите команду агентов для запуска:")
    print("1. 📈 Crypto Trading Swarm (Хедж-фонд)")
    print("2. 💻 Dev Squad (Разработчики + Злой Критик)")
    print("3. ✍️ Content Factory (SEO & Копирайтинг)")
    print("4. 🕵️ OSINT Research (Глубокий поиск)")

    choice = input("\nВведите номер (1-4): ")

    if choice == '1':
        print("\n--- Запуск Торгового Роя ---")
        # В реальном проекте здесь будет запрос к API биржи
        mock_data = input("Введите контекст рынка (или нажмите Enter для демо-данных): ")
        if not mock_data:
            mock_data = "BTC/USDT цена 95000, RSI 75 (перекуплен), новости нейтральные, объемы падают."
        result = run_trading_swarm(mock_data)
        print("\n[РЕЗУЛЬТАТ]:\n", result)

    elif choice == '2':
        print("\n--- Запуск IT-отдела ---")
        idea = input("Опишите идею проекта/фичи: ")
        if idea:
            result = run_dev_squad(idea)
            print("\n[РЕЗУЛЬТАТ]:\n", result)

    elif choice == '3':
        print("\n--- Запуск Фабрики Контента ---")
        topic = input("Введите тему для статьи/поста: ")
        if topic:
            result = run_content_factory(topic)
            print("\n[РЕЗУЛЬТАТ]:\n", result)

    elif choice == '4':
        print("\n--- Запуск OSINT Разведки ---")
        query = input("Что (или кого) нужно исследовать?: ")
        if query:
            result = run_osint_research(query)
            print("\n[РЕЗУЛЬТАТ]:\n", result)

    else:
        print("Неверный выбор. Завершение.")

if __name__ == "__main__":
    # Проверка ключа (простая)
    if not os.environ.get("OPENAI_API_KEY"):
        print("⚠️ ВНИМАНИЕ: Не найден OPENAI_API_KEY. Убедитесь, что он установлен в переменных среды.")
        # os.environ["OPENAI_API_KEY"] = "sk-..." # Можно раскомментировать и вставить сюда для теста

    main()