# -*- coding: utf-8 -*-
"""OSINT Team

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gp1Ls25Ohnv5kiBSIJxAZx9mxS2PvMB-
"""

from crewai import Agent, Task, Crew, Process
# Примечание: Для реального OSINT агенту Scraper понадобятся Tools (инструменты)
# вроде SerperDevTool или Selenium, которые нужно настроить отдельно.
# Здесь базовая логика.

def run_osint_research(query):
    """
    Запускает команду глубокого поиска.
    Аргумент: query (цель исследования).
    """

    # 1. Планировщик
    planner = Agent(
        role='Intelligence Planner',
        goal='Разбить задачу на векторы поиска.',
        backstory='''Ты стратег. Ты понимаешь, что информацию часто прячут.
        Ты составляешь список неочевидных поисковых запросов.''',
        verbose=True
    )

    # 2. Ресерчер (Скрейпер)
    researcher = Agent(
        role='Deep Web Researcher',
        goal='Найти факты по плану планировщика.',
        backstory='''Ты умеешь гуглить как бог. Ты ищешь PDF, форумы, архивы.
        Ты собираешь сырые данные и ссылки.''',
        verbose=True
    )

    # 3. Аналитик (Синтезатор)
    synthesizer = Agent(
        role='Intelligence Analyst',
        goal='Собрать отчет из сырых данных.',
        backstory='''Ты сводишь разрозненные факты в единую картину.
        Ты пишешь краткое резюме (Executive Summary) и список инсайтов.''',
        verbose=True
    )

    # Задачи
    t1 = Task(
        description=f'Составь стратегию поиска для: "{query}".',
        expected_output='Список поисковых запросов и ресурсов.',
        agent=planner
    )

    t2 = Task(
        description='(Симуляция) Проведи поиск по стратегии. Собери ключевые факты.',
        expected_output='Сырые данные и ссылки.',
        agent=researcher
    )

    t3 = Task(
        description='Проанализируй данные и составь финальное досье/отчет.',
        expected_output='Структурированный отчет.',
        agent=synthesizer
    )

    crew = Crew(
        agents=[planner, researcher, synthesizer],
        tasks=[t1, t2, t3],
        process=Process.sequential
    )

    return crew.kickoff()