"""Dry-run stub: collects inputs, formats digest, prints preview.

Actual sending via Claude Desktop routine (scripts/claude_routines/.../SKILL.md)
OR manual invocation in a Krab userbot session.
"""

from __future__ import annotations

import subprocess
import textwrap
from datetime import datetime


MAX_DIGEST_CHARS = 3500

DIGEST_TEMPLATE = """\
🦀 **Krab × Chado Weekly Sync** — {date}

## 🔧 Top 5 changes this week
{top_features}

## 🌐 Ecosystem snapshot
{ecosystem_summary}

## 💬 Sync request
Chado, что из этого интересно для cross-AI review?
Any parallel work on your side worth surfacing?

---
*Auto-generated by krab-openclaw-chado-sync routine*
"""


def get_git_log_7d(repo_path: str = "/Users/pablito/Antigravity_AGENTS/Краб") -> list[str]:
    """Возвращает список коммитов за последние 7 дней (oneline)."""
    result = subprocess.run(
        ["git", "log", "--since=7 days ago", "--oneline"],
        cwd=repo_path,
        capture_output=True,
        text=True,
        timeout=10,
    )
    lines = [l.strip() for l in result.stdout.splitlines() if l.strip()]
    return lines


def pick_top_features(commits: list[str], n: int = 5) -> list[str]:
    """Выбирает top N feat/fix коммитов; fallback — первые N."""
    priority = [c for c in commits if c.split(" ", 1)[-1].startswith(("feat", "fix"))]
    pool = priority if priority else commits
    return pool[:n]


def format_digest(
    top_features: list[str],
    ecosystem_summary: str = "N/A (panel offline or dry-run)",
) -> str:
    """Форматирует дайджест и обрезает до MAX_DIGEST_CHARS."""
    numbered = "\n".join(f"{i+1}. {c}" for i, c in enumerate(top_features)) or "No commits this week."
    digest = DIGEST_TEMPLATE.format(
        date=datetime.now().strftime("%Y-%m-%d"),
        top_features=numbered,
        ecosystem_summary=ecosystem_summary,
    )
    if len(digest) > MAX_DIGEST_CHARS:
        # Обрезаем ecosystem_summary, сохраняем структуру
        excess = len(digest) - MAX_DIGEST_CHARS + 3
        trimmed_eco = ecosystem_summary[: max(10, len(ecosystem_summary) - excess)] + "…"
        digest = DIGEST_TEMPLATE.format(
            date=datetime.now().strftime("%Y-%m-%d"),
            top_features=numbered,
            ecosystem_summary=trimmed_eco,
        )
    return digest[:MAX_DIGEST_CHARS]


def dry_run_preview() -> str:
    """Собирает данные и выводит preview дайджеста без отправки."""
    commits = get_git_log_7d()
    features = pick_top_features(commits)
    digest = format_digest(features)

    preview = textwrap.dedent(f"""\
        === DRY-RUN PREVIEW ===
        Commits found (7d): {len(commits)}
        Top features selected: {len(features)}
        Digest length: {len(digest)} chars (limit {MAX_DIGEST_CHARS})
        ----------------------
        {digest}
        === END PREVIEW ===
    """)
    return preview


if __name__ == "__main__":
    print(dry_run_preview())
