# -*- coding: utf-8 -*-
"""Main Entry Point

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZOGTxnMYg7Rz_IIxlgqOD3PmErK11vPS
"""

# -*- coding: utf-8 -*-
"""
Krab v2.0 - Core Entry Point (Orchestrator)
Этот файл связывает Pyrogram, Model Router и Context Manager.
"""

import os
import asyncio
import logging
from dotenv import load_dotenv
from pyrogram import Client, filters, idle, enums
from pyrogram.types import Message

# Импорт наших новых ядерных модулей
from src.core.model_manager import ModelRouter
from src.core.context_manager import ContextKeeper
from src.modules.perceptor import Perceptor

# Настройка логирования
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler("logs/krab.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger("KrabMain")

# Загрузка переменных
load_dotenv()

# Конфигурация
API_ID = os.getenv("TELEGRAM_API_ID")
API_HASH = os.getenv("TELEGRAM_API_HASH")
SESSION_NAME = os.getenv("TELEGRAM_SESSION_NAME", "krab_v2_session")

# Инициализация компонентов
# Config for Perceptor (loaded from env or defaults)
perceptor_config = {
    "WHISPER_MODEL": "mlx-community/whisper-large-v3-turbo"
}

router = ModelRouter(config=os.environ)
memory = ContextKeeper()
perceptor = Perceptor(config=perceptor_config) # Модуль "Глаза и Уши"

# Инициализация клиента (Userbot)
app = Client(SESSION_NAME, api_id=API_ID, api_hash=API_HASH)

# --- GLOBAL DEBUG LOGGER ---
@app.on_message(group=-1)
async def debug_logger(client, message: Message):
    sender = message.from_user.username if message.from_user else "Unknown"
    msg_type = message.media.value if message.media else "Text"
    logger.info(f"🔍 DEBUG: New Message from @{sender} ({message.chat.id}). Type: {msg_type}. Text: {message.text or message.caption or 'None'}")

# --- EVENT HANDLERS ---

@app.on_message(filters.command("status", prefixes="!"))
async def status_check(client, message):
    """Быстрая проверка здоровья систем (Router + Local Server)."""
    # Проверка прав (как в auto_reply)
    allowed_users = os.getenv("ALLOWED_USERS", "").split(",")
    allowed_users = [u.strip() for u in allowed_users if u.strip()]
    owner = os.getenv("OWNER_USERNAME", "").replace("@", "").strip()
    if owner: allowed_users.append(owner)
    
    sender = message.from_user.username if message.from_user else "Unknown"
    sender_id = str(message.from_user.id) if message.from_user else "0"
    
    if sender not in allowed_users and sender_id not in allowed_users:
        return

    msg_method = message.edit_text if message.from_user.is_self else message.reply_text
    status_msg = await msg_method("🦀 Checking systems...")

    # Проверка локального AI
    await router.check_local_health()
    local_status = "🟢 Online" if router.is_local_available else "🔴 Offline"
    model_name = router.active_local_model or "None"

    text = (
        f"**Krab v2.0 Systems:**\n"
        f"🧠 **AI Core:** Hybrid (Cloud + Local)\n"
        f"🏠 **Local LLM:** {local_status} ({model_name})\n"
        f"👂 **Ears:** Active (Whisper)\n"
        f"👁️ **Eyes:** Active (Vision)"
    )
    
    if message.from_user.is_self:
        await status_msg.edit_text(text)
    else:
        await status_msg.edit_text(text) # reply_text returns a message which we can edit

@app.on_message(filters.command("summary", prefixes="!"))
async def summarize_chat(client, message):
    """Саммаризация переписки (последние 50-100 сообщений)."""
    # Проверка прав
    sender = message.from_user.username if message.from_user else "Unknown"
    allowed_users = os.getenv("ALLOWED_USERS", "").split(",")
    allowed_users = [u.strip() for u in allowed_users if u.strip()]
    owner = os.getenv("OWNER_USERNAME", "").replace("@", "").strip()
    if owner: allowed_users.append(owner)

    if sender not in allowed_users and not message.from_user.is_self:
        return

    notification = await message.reply_text("🧐 Читаю историю...")
    
    # 1. Получаем контекст (последние 100 сообщений)
    # limit=0 gets all, but lets keep it 100 for safety
    history = memory.get_recent_context(message.chat.id, limit=100)
    
    if not history:
        await notification.edit_text("❌ История пуста.")
        return

    # 2. Формируем промпт
    messages_text = ""
    for msg in history:
        role = msg.get('user', msg.get('role', 'unknown'))
        content = msg.get('text', msg.get('content', '[media]'))
        messages_text += f"{role}: {content}\n"

    prompt = (
        "Проанализируй эту переписку и составь краткое резюме (Summary).\n"
        "Выдели главные темы, договоренности и важные моменты.\n"
        "Стиль: Краткий, деловой, структурированный булллитами.\n\n"
        f"Переписка:\n{messages_text}"
    )

    # 3. Отправляем в AI
    summary = await router.route_query(prompt, task_type='chat')
    
    await notification.edit_text(f"📝 **Summary:**\n\n{summary}")

@app.on_message(filters.command("say", prefixes="!"))
async def say_text(client, message):
    """Text-to-Speech: !say <text> or reply to text."""
    # Check permissions (reuse logic or improve)
    sender = message.from_user.username if message.from_user else "Unknown"
    allowed_users = os.getenv("ALLOWED_USERS", "").split(",")
    allowed_users = [u.strip() for u in allowed_users if u.strip()]
    owner = os.getenv("OWNER_USERNAME", "").replace("@", "").strip()
    if owner: allowed_users.append(owner)

    if sender not in allowed_users and not message.from_user.is_self:
        return

    # Determine text
    text_to_speak = ""
    if len(message.command) > 1:
        text_to_speak = message.text.split(" ", 1)[1]
    elif message.reply_to_message:
        text_to_speak = message.reply_to_message.text or message.reply_to_message.caption
    
    if not text_to_speak:
         await message.reply_text("🗣️ Укажи текст: `!say Привет` или ответь на сообщение.")
         return

    notification = await message.reply_text("🗣️ Генерирую голос...")
    
    # Call Perceptor TTS
    # Default voice is Milena (Russian). 
    voice_path = await perceptor.speak(text_to_speak, voice="Milena")
    
    if voice_path and os.path.exists(voice_path):
        await message.reply_voice(voice_path, caption=f"🗣️ **Said:** {text_to_speak[:20]}...")
        await notification.delete()
        os.remove(voice_path)
    else:
        await notification.edit_text("❌ Ошибка генерации голоса.")

@app.on_message(filters.command("translate", prefixes="!"))
async def translate_text(client, message):
    """Перевод текста: !translate <text> или реплаем на сообщение.
    По умолчанию переводит: RU -> EN, EN -> RU (авто-определение).
    Можно указать язык: !translate en Привет мир
    """
    sender = message.from_user.username if message.from_user else "Unknown"
    allowed_users = os.getenv("ALLOWED_USERS", "").split(",")
    allowed_users = [u.strip() for u in allowed_users if u.strip()]
    owner = os.getenv("OWNER_USERNAME", "").replace("@", "").strip()
    if owner: allowed_users.append(owner)
    if sender not in allowed_users and not message.from_user.is_self:
        return

    # Определяем текст для перевода
    text_to_translate = ""
    target_lang = None  # Авто-определение

    if len(message.command) > 1:
        args = message.text.split(" ", 1)[1]
        # Проверяем, не указан ли язык первым словом
        first_word = args.split(" ", 1)[0].lower()
        if first_word in ["en", "ru", "es", "fr", "de", "zh", "ja", "ko", "ar", "pt", "it"]:
            target_lang = first_word
            text_to_translate = args.split(" ", 1)[1] if len(args.split(" ", 1)) > 1 else ""
        else:
            text_to_translate = args
    elif message.reply_to_message:
        text_to_translate = message.reply_to_message.text or message.reply_to_message.caption

    if not text_to_translate:
        await message.reply_text("🌐 Укажи текст: `!translate Привет` или ответь на сообщение.\n"
                                 "Можно указать язык: `!translate en Привет мир`")
        return

    notification = await message.reply_text("🌐 Перевожу...")

    # Формируем промпт для перевода
    if target_lang:
        lang_map = {"en": "English", "ru": "Russian", "es": "Spanish", "fr": "French",
                    "de": "German", "zh": "Chinese", "ja": "Japanese", "ko": "Korean",
                    "ar": "Arabic", "pt": "Portuguese", "it": "Italian"}
        lang_name = lang_map.get(target_lang, target_lang)
        prompt = f"Переведи этот текст на {lang_name}. Выведи ТОЛЬКО перевод, без пояснений.\n\n{text_to_translate}"
    else:
        prompt = ("Определи язык этого текста. Если это русский — переведи на английский. "
                  "Если это любой другой язык — переведи на русский. "
                  "Выведи ТОЛЬКО перевод, без пояснений.\n\n"
                  f"{text_to_translate}")

    translation = await router.route_query(prompt, task_type='chat')
    await notification.edit_text(f"🌐 **Translation:**\n\n{translation}")

@app.on_message(filters.command("diagnose", prefixes="!"))
async def diagnose_system(client, message):
    """Полная диагностика всех подсистем Краба."""
    sender = message.from_user.username if message.from_user else "Unknown"
    allowed_users = os.getenv("ALLOWED_USERS", "").split(",")
    allowed_users = [u.strip() for u in allowed_users if u.strip()]
    owner = os.getenv("OWNER_USERNAME", "").replace("@", "").strip()
    if owner: allowed_users.append(owner)
    if sender not in allowed_users and not message.from_user.is_self:
        return

    notification = await message.reply_text("🔍 Запускаю диагностику...")

    import psutil
    import platform
    
    # 1. Системные метрики
    cpu = psutil.cpu_percent(interval=0.5)
    ram = psutil.virtual_memory()
    disk = psutil.disk_usage('/')
    
    # 2. Проверка Local AI
    await router.check_local_health()
    local_status = "🟢 Online" if router.is_local_available else "🔴 Offline"
    local_model = router.active_local_model or "N/A"
    
    # 3. Проверка Gemini
    gemini_status = "🟢 Key Present" if router.gemini_key else "🔴 No Key"
    
    # 4. Дискеция памяти бота
    history_count = len(memory.get_recent_context(message.chat.id, limit=0))
    
    # 5. Python / Platform info
    py_ver = platform.python_version()
    mac_ver = platform.mac_ver()[0]
    chip = platform.processor() or "Apple Silicon"
    
    text = (
        f"**🦀 Krab v2.0 — Полная Диагностика**\n\n"
        f"**Система:**\n"
        f"├ macOS {mac_ver} ({chip})\n"
        f"├ Python {py_ver}\n"
        f"├ CPU: {cpu}%\n"
        f"├ RAM: {ram.percent}% ({ram.used // (1024**3)}/{ram.total // (1024**3)} GB)\n"
        f"└ Disk: {disk.percent}% ({disk.used // (1024**3)}/{disk.total // (1024**3)} GB)\n\n"
        f"**AI Core:**\n"
        f"├ Local LLM: {local_status} ({local_model})\n"
        f"├ Gemini API: {gemini_status}\n"
        f"└ Whisper: 🟢 Active ({perceptor.whisper_model})\n\n"
        f"**Modules:**\n"
        f"├ 👂 Ears (STT): Active\n"
        f"├ 🗣️ Voice (TTS): Active (Milena)\n"
        f"├ 👁️ Eyes (Vision): Active\n"
        f"├ 📝 Summary: Active\n"
        f"├ 🌐 Translate: Active\n"
        f"└ 💾 Memory: {history_count} msgs (this chat)\n\n"
        f"**Uptime:** Running as @{(await client.get_me()).username}"
    )
    
    await notification.edit_text(text)

@app.on_message(filters.command("code", prefixes="!"))
async def generate_code(client, message):
    """Генерация кода: !code <задача>. Используя AI для написания кода."""
    sender = message.from_user.username if message.from_user else "Unknown"
    allowed_users = os.getenv("ALLOWED_USERS", "").split(",")
    allowed_users = [u.strip() for u in allowed_users if u.strip()]
    owner = os.getenv("OWNER_USERNAME", "").replace("@", "").strip()
    if owner: allowed_users.append(owner)
    if sender not in allowed_users and not message.from_user.is_self:
        return

    task = ""
    if len(message.command) > 1:
        task = message.text.split(" ", 1)[1]
    elif message.reply_to_message:
        task = message.reply_to_message.text or message.reply_to_message.caption

    if not task:
        await message.reply_text("💻 Опиши задачу: `!code Напиши парсер JSON`")
        return

    notification = await message.reply_text("💻 Генерирую код...")

    prompt = (
        "Ты — опытный Python-разработчик. "
        "Напиши чистый, рабочий код для решения задачи. "
        "Верни ТОЛЬКО код внутри блока ```python ... ```. "
        "Добавь краткие комментарии на русском.\n\n"
        f"Задача: {task}"
    )

    code = await router.route_query(prompt, task_type='coding')
    await notification.edit_text(f"💻 **Code:**\n\n{code}")

@app.on_message(filters.command("exec", prefixes="!"))
async def exec_python(client, message):
    """Выполнение Python-кода (ТОЛЬКО для владельца).
    !exec print('hello') или реплай на сообщение с кодом.
    ⚠️ Опасно! Только для OWNER.
    """
    # СТРОГО только владелец
    owner = os.getenv("OWNER_USERNAME", "").replace("@", "").strip()
    sender = message.from_user.username if message.from_user else "Unknown"
    
    if sender != owner and not message.from_user.is_self:
        await message.reply_text("🔒 Эта команда доступна только владельцу.")
        return

    code = ""
    if len(message.command) > 1:
        code = message.text.split(" ", 1)[1]
    elif message.reply_to_message:
        code = message.reply_to_message.text or message.reply_to_message.caption

    if not code:
        await message.reply_text("⚙️ Укажи код: `!exec print('hello')`")
        return

    # Убираем markdown-обёртку если есть
    if code.startswith("```") and code.endswith("```"):
        code = code.strip("```")
        if code.startswith("python\n"):
            code = code[7:]

    notification = await message.reply_text("⚙️ Выполняю...")

    import io
    import sys
    import traceback

    # Безопасное выполнение с перехватом stdout/stderr
    old_stdout = sys.stdout
    old_stderr = sys.stderr
    sys.stdout = captured_out = io.StringIO()
    sys.stderr = captured_err = io.StringIO()

    try:
        # Таймаут 10 секунд (защита от бесконечных циклов)
        exec(code, {"__builtins__": __builtins__})
        output = captured_out.getvalue()
        error = captured_err.getvalue()
        
        result = ""
        if output:
            result += f"📤 **Output:**\n```\n{output[:3000]}\n```\n"
        if error:
            result += f"⚠️ **Stderr:**\n```\n{error[:1000]}\n```\n"
        if not output and not error:
            result = "✅ Код выполнен без вывода."
        
        await notification.edit_text(result)
    except Exception as e:
        tb = traceback.format_exc()
        await notification.edit_text(f"❌ **Error:**\n```\n{tb[-2000:]}\n```")
    finally:
        sys.stdout = old_stdout
        sys.stderr = old_stderr

@app.on_message(filters.command("help", prefixes="!"))
async def show_help(client, message):
    """Справка по командам бота."""
    text = (
        "**🦀 Krab v2.0 — Команды:**\n\n"
        "**Основные:**\n"
        "`!status` — Проверка здоровья AI систем\n"
        "`!diagnose` — Полная диагностика (CPU, RAM, модули)\n"
        "`!help` — Эта справка\n\n"
        "**AI:**\n"
        "`!summary` — Саммари последних 100 сообщений\n"
        "`!translate [lang] <text>` — Перевод (авто RU↔EN)\n"
        "`!say <text>` — Озвучить (голосовое сообщение)\n"
        "`!code <задача>` — Генерация Python-кода\n\n"
        "**Dev (Owner only):**\n"
        "`!exec <code>` — Выполнение Python кода\n\n"
        "**Автоматические:**\n"
        "🎤 Голосовые → Авто-транскрипция + ответ\n"
        "📸 Фото → Авто-анализ + комментарий\n"
        "💬 Текст → Авто-ответ (для белого списка)\n\n"
        "**Подсказки:**\n"
        "• Реплай работает для: `!translate`, `!say`, `!code`, `!exec`\n"
        "• `!translate en Текст` — перевод на конкретный язык"
    )
    await message.reply_text(text)

@app.on_message(filters.voice | filters.audio | filters.document)
async def handle_audio(client, message: Message):
    """Автоматическая обработка голосовых (через Perceptor)."""
    # Проверяем, аудио ли это, т.к. фильтр document ловит все
    is_audio = message.voice or message.audio or (message.document and "audio" in message.document.mime_type)
    
    if not is_audio:
        return # Skip non-audio documents

    # Определяем объект медиа
    media = message.voice or message.audio or message.document
    if not media:
        return

    # Логика: Если сообщение в ЛС мне или я упомянут - транскрибировать
    is_private = message.chat.type == enums.ChatType.PRIVATE
    if is_private or (message.caption and "!txt" in message.caption):
        logger.info(f"Processing audio from {message.chat.id}")

        # Скачиваем файл
        file_path = await message.download(file_name=f"artifacts/downloads/{media.file_unique_id}.ogg")
        
        # Транскрибируем (Локально или через API)
        notification = await message.reply_text("👂 Слушаю...")
        
        # Проверяем, существует ли файл (иногда download возвращает None при ошибке)
        if not file_path or not os.path.exists(file_path):
             await notification.edit_text("❌ Ошибка скачивания файла.")
             return

        text = await perceptor.transcribe(file_path, router)

        # Сохраняем в контекст
        memory.save_message(message.chat.id, {"role": "audio_transcript", "content": text})

        await notification.edit_text(f"**Transcript:** `{text}`\n\n🤔 Думаю...")
        
        # Запрашиваем ответ у AI
        context = memory.get_recent_context(message.chat.id, limit=5)
        voice_prompt = f"[Голосовое сообщение]: {text}"
        
        response_text = await router.route_query(
            prompt=voice_prompt,
            task_type='chat',
            context=context
        )
        
        await message.reply_text(response_text)
        memory.save_message(message.chat.id, {"role": "assistant", "text": response_text})
        
        # Финализируем уведомление
        await notification.edit_text(f"**Transcript:**\n\n{text}")

        # Удаляем файл для экономии места
        os.remove(file_path)

@app.on_message(filters.photo)
async def handle_vision(client, message: Message):
    """Обработка изображений (включая HEIC)."""
    # Реагируем если есть caption !scan или !vision, ИЛИ если это ЛС с ботом (авто-скан)
    is_private = message.chat.type == enums.ChatType.PRIVATE
    should_scan = (message.caption and ("!scan" in message.caption or "!vision" in message.caption)) or is_private
    
    if should_scan:
        notification = await message.reply_text("👁️ Смотрю...")
        file_path = await message.download(file_name=f"artifacts/downloads/{message.file.unique_id}")
        
        # Анализ изображения
        description = await perceptor.analyze_image(file_path, router, prompt="Что на изображении? Опиши подробно.")
        memory.save_message(message.chat.id, {"role": "vision_analysis", "content": description})
        
        await notification.edit_text(f"👁️ **Vision:** `{description}`\n\n🤔 Думаю...")
        
        # Запрашиваем реакцию AI
        context = memory.get_recent_context(message.chat.id, limit=5)
        vision_prompt = f"[Пользователь прислал фото]: {description}. Прокомментируй или ответь на вопрос."
        if message.caption:
            vision_prompt += f"\nПодпись: {message.caption}"

        response_text = await router.route_query(
            prompt=vision_prompt,
            task_type='chat',
            context=context
        )
        
        await message.reply_text(response_text)
        memory.save_message(message.chat.id, {"role": "assistant", "text": response_text})
        
        await notification.edit_text(f"**Vision Analysis:**\n\n{description}")
        os.remove(file_path)

@app.on_message(filters.text & ~filters.me & ~filters.bot)
async def auto_reply_logic(client, message: Message):
    """
    Умный автоответчик.
    Срабатывает, если:
    1. Это ЛС или упоминание.
    2. Пользователь в белом списке.
    """
    if message.text is None: return # Защита от странных апдейтов

    # 1. Проверка доступа
    allowed_users = os.getenv("ALLOWED_USERS", "").split(",")
    # Очистка списка от пробелов и пустых строк
    allowed_users = [u.strip() for u in allowed_users if u.strip()]
    
    # Добавляем владельца
    owner = os.getenv("OWNER_USERNAME", "").replace("@", "").strip()
    if owner:
        allowed_users.append(owner)

    sender = message.from_user.username if message.from_user else "Unknown"
    sender_id = str(message.from_user.id) if message.from_user else "0"
    
    logger.info(f"📩 Msg from @{sender}. Allowed: {allowed_users}")

    # Если в списке есть админы по ID - можно добавить проверку ID
    # Пока проверяем по username (упрощенно)
    if sender not in allowed_users and sender_id not in allowed_users:
        logger.info(f"⛔ Ignored unauthorized message from @{sender}")
        return

    # 2. Сохраняем контекст (User Msg)
    memory.save_message(message.chat.id, {
        "user": sender,
        "text": message.text
    })

    # 3. Маршрутизация запроса
    # Получаем историю для контекста
    context = memory.get_recent_context(message.chat.id, limit=10)
    
    # Отправляем "печатает..."
    await client.send_chat_action(message.chat.id, action=enums.ChatAction.TYPING)

    # Запрашиваем ответ у AI
    response_text = await router.route_query(
        prompt=message.text,
        task_type='chat',
        context=context
    )

    # 4. Отправляем ответ
    await message.reply_text(response_text)

    # 5. Сохраняем контекст (Bot Msg)
    memory.save_message(message.chat.id, {
        "role": "assistant",
        "text": response_text
    })

# --- MAIN LOOP ---

async def main():
    logger.info("Starting Krab v2.0...")
    await app.start()

    # Предварительная проверка роутера
    await router.check_local_health()
    me = await app.get_me()
    logger.info(f"Logged in as {me.first_name} (@{me.username})")
    
    # Notify Owner (@p0lrd)
    try:
        await app.send_message("p0lrd", "🦀 Krab v2.0 Online.\n✅ System Prompt: Loaded (v2).\n✅ Tests: 6/6 Passed (Context, Perceptor).\n✅ Audio/Vision: Active.")
    except Exception as e:
        logger.warning(f"Could not key message to @p0lrd: {e}")

    await idle()
    await app.stop()

if __name__ == "__main__":
    app.run(main())